modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
[[mods]]
modId="packetweave"
version="${mod_version}"
displayName="PacketWeave"
authors="NsTut"
description='''A safe and bounded binary transfer engine for Minecraft mods.'''
[[dependencies.packetweave]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
